version: "2"

networks:
  test:

services:
  {{range .PeerOrgCps}}
  ca-{{.GetNameToLower}}:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.{{.GetNameToLower}}.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.{{.GetNameToLower}}.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.{{.GetNameToLower}}.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports:
      - "{{.GetPortOfCA}}:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/{{.GetNameToLower}}.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel/crypto-config/peerOrganizations/{{.GetNameToLower}}.example.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.{{.GetNameToLower}}.example.com
    hostname: ca.{{.GetNameToLower}}.example.com
    networks:
      - test
    {{end}}

  {{range .OrdererCps}}
  {{.HostName}}.example.com:
    container_name: {{.HostName}}.example.com
    image: hyperledger/fabric-orderer:2.1
    dns_search: .
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT={{.GetGeneralPortOfOrderer}}
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - {{.GetGeneralPortOfOrderer}}:{{.GetGeneralPortOfOrderer}}
      - {{.GetOperationPortOfOrderer}}:8443
    networks:
      - test
    volumes:
      - ./channel/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/{{.HostName}}.example.com/msp:/var/hyperledger/orderer/msp
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/{{.HostName}}.example.com/tls:/var/hyperledger/orderer/tls
    {{end}}
{{range .PeerOrgCps}}
  {{$NameToLower := .GetNameToLower}}
  {{$Name := .Name}}
  {{$IdOfPeerOrg := .GetIdOfPeerOrg}}
  {{range .GenListFromPeers}}
  couchdb{{GetIdOfCouchDB $IdOfPeerOrg .}}:
    container_name: couchdb{{GetIdOfCouchDB $IdOfPeerOrg .}}
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - {{GetPortOfCouchDB $IdOfPeerOrg .}}:5984
    networks:
      - test

  peer{{.}}.{{$NameToLower}}.example.com:
    container_name: peer{{.}}.{{$NameToLower}}.example.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID={{$Name}}MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test
      - CORE_PEER_ID=peer{{.}}.{{$NameToLower}}.example.com
      - CORE_PEER_ADDRESS=peer{{.}}.{{$NameToLower}}.example.com:{{GetGeneralPortOfPeer $IdOfPeerOrg .}}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:{{GetGeneralPortOfPeer $IdOfPeerOrg .}}
      - CORE_PEER_CHAINCODEADDRESS=peer{{.}}.{{$NameToLower}}.example.com:{{GetChaincodePortOfPeer $IdOfPeerOrg .}}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:{{GetChaincodePortOfPeer $IdOfPeerOrg .}}
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer{{GetIdOfBootstrapNode .}}.{{$NameToLower}}.example.com:{{GetPortOfBootstrapPeer $IdOfPeerOrg .}}
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer{{.}}.{{$NameToLower}}.example.com:{{GetGeneralPortOfPeer $IdOfPeerOrg .}}

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb{{GetIdOfCouchDB $IdOfPeerOrg .}}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - couchdb{{GetIdOfCouchDB $IdOfPeerOrg .}}
    ports:
      - {{GetGeneralPortOfPeer $IdOfPeerOrg .}}:{{GetGeneralPortOfPeer $IdOfPeerOrg .}}
    volumes:
      - ./channel/crypto-config/peerOrganizations/{{$NameToLower}}.example.com/peers/peer{{.}}.{{$NameToLower}}.example.com/msp:/etc/hyperledger/crypto/peer/msp
      - ./channel/crypto-config/peerOrganizations/{{$NameToLower}}.example.com/peers/peer{{.}}.{{$NameToLower}}.example.com/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./channel/:/etc/hyperledger/channel/
    networks:
      - test
    {{end}}
{{end}}